### PR TITLE
Allow disabled selects

### PR DESCRIPTION
**Pull request by timothyarmes**
Take into account the `disabled` attribute on the select input type by
adding the `disabled` class.

### CODE REVIEW

**Comment by fabienb4** [comment]
You can disable a select by using `classNames="disabled"` (works with pretty much every components).

For simplicity's sake, I think leaving it this way will be easier (adding a property for every possible modifiers which use a class would be a code readability nightmare).

```
{{> afQuickField name="items" type="select" link=true pointing=true disabled=true scrolling=true fluid=true}}
```

vs

```
{{> afQuickField name="items" type="select" classNames="link pointing disabled scrolling fluid"}}
```

It might be justified for disabled though.
I'll leave this open for a few days, see what people think.

**Comment by abernix** [comment]
I think class controls it just fine and would leave it as is.  Better interoperability with any other package/module/whatever that (theoretically) wants to "disable" a form.

**Comment by timothyarmes** [comment]
Well, if you create a [disabled](https://github.com/aldeed/meteor-autoform#disabled) form type using auto form then the semantic elements currently don't work as they should...

**Comment by steve-ross** [comment]
I agree with @timothyarmes, it would be better to support the 'autoform' way

**Comment by fabienb4** [comment]
Agreed. The fact that Autoform requires per input `disabled` detection for disabled form type justifies the separate property.

Thanks @timothyarmes

**Pull request closed without merging**
